# This file configures the build and deployment settings for Netlify.
# Copy the contents of this file and paste it into a new file named "netlify.toml" in the root of your project.

# The [build] block tells Netlify which directory contains the final static
# files to be published to the web.
[build]
  # This should be the root directory of your site where index.html is located.
  publish = "/"

# The [functions] block tells Netlify where to find our serverless functions.
# These are our secure backend API endpoints.
[functions]
  directory = "netlify/functions/"

# This is the crucial redirect rule to fix the 404 errors.
# It tells Netlify to route any request starting with "/api/" to the correct serverless function.
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
